name: Build & Test
on:
  workflow_call:
    inputs:
      platform_name:
        required: true
        type: string
      image_name:
        required: true
        type: string
      std_version:
        required: true
        type: string
env:
  BUILD_TYPE: Debug
jobs:
  build:
    runs-on: ${{inputs.image_name}}
    steps:
      - uses: actions/checkout@v3
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: C:/Program Files/LLVM
          key: llvm-15
      - name: Install LLVM & Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: 15.0
          cached: ${{steps.cache-llvm.outputs.cache-hit}}
      - name: Initialize submodules
        run: git submodule update --init
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Configure CMake (${{inputs.platform_name}})
        run: >-
          cmake -G Ninja -B ${{github.workspace}}/build-${{inputs.platform_name}} 
          -DCMAKE_C_FLAGS=TRUE 
          -DCMAKE_C_COMPILER="C:/Program Files/LLVM/bin/clang.exe"
          -DCMAKE_C_COMPILER_ID="Clang"
          -DCMAKE_CXX_FLAGS=TRUE
          -DCMAKE_CXX_COMPILER="C:/Program Files/LLVM/bin/clang.exe" 
          -DCMAKE_CXX_COMPILER_ID="Clang"
          -DCMAKE_LINKER="C:/Program Files/LLVM/bin/lld-link.exe" 
          -DCMAKE_SYSTEM_NAME="Generic"
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
          -DGTEST_USE_OWN_TR1_TUPLE=1 
          -DCMAKE_CXX_STANDARD=${{inputs.std_version}}
      - name: Build (${{inputs.platform_name}})
        run: >-
          cmake --build ${{github.workspace}}/build-${{inputs.platform_name}} 
          --config ${{env.BUILD_TYPE}} --clean-first
      - name: Test (${{inputs.platform_name}})
        working-directory: ${{github.workspace}}/build-${{inputs.platform_name}}
        run: ctest -C ${{env.BUILD_TYPE}}